# ==================
# tmux configuration
# ==================
# quick edit aliased to tconf in zshrc
# ------------------


# ===========
# Keybindings
# =========

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf reloaded"   

# use ctrl + space as prefix key
unbind C-b
unbind C-space
set-option -g prefix C-space
bind-key C-space send-prefix

# split panes using | and _
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Increase tmux history from 2000 to 5000 lines
set-option -g history-limit 5000

# Renumber windows and panes in the array if an eariler one has been deleted
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1


# Preserve the current path when making new windows and panes
bind c new-window -c "#{pane_current_path}"

# Toggle to the last window
bind Space last-window

# Toggle to the last session
bind-key C-Space switch-client -l

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

# =========================
# Interface, Colors, Design
# =========================

# Upgrade $TERM
set -g default-terminal "screen-256color"

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour cyan

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=#222222'
set -g pane-active-border-style 'fg=#555555'

# ---------
# statusbar
# ---------

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Message color
set -g message-style 'fg=black bold bg=yellow'

# Layout
# set -g status-position top
# set -g status-justify left
# set -g status-style 'fg=#eeeeee bg=#222222'

# set -g status-left ''
# set -g status-left-length 10

# set -g status-right-style 'fg=#eeeeee bg=#222222'
# set -g status-right '%Y-%m-%d %H:%M '
# set -g status-right-length 50

# setw -g window-status-current-style 'fg=#eeeeee bg=#222222 bold'
# setw -g window-status-current-format ' #I #W #F '

# setw -g window-status-style 'fg=#eeeeee bg=#222222 bold'
# setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

# setw -g window-status-bell-style 'fg=black bg=yellow bold'

# -------
# Plugins
# -------

# status bar (dotbar) theme
set -g @tmux-dotbar-position "top"
set -g @tmux-dotbar-bg "#222222"
set -g @tmux-dotbar-fg "grey"
set -g @tmux-dotbar-fg-current "yellow"
set -g @tmux-dotbar-fg-session "white"
set -g @tmux-dotbar-fg-prefix "yellow"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# =======
# Credits
# =======
# - https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
#
# -------